#!/usr/bin/sh

npm install -D --legacy-peer-deps  \
     @babel/cli @babel/core @babel/eslint-parser @babel/plugin-proposal-class-properties \
     @babel/plugin-proposal-object-rest-spread @babel/preset-env @babel/preset-flow \
     @babel/preset-react @types/react @types/react-dom babel-loader clean-webpack-plugin \
     cross-env css-loader eslint eslint-config-babel eslint-config-prettier eslint-plugin-flowtype \
     eslint-plugin-react flow-bin html-webpack-plugin jest prettier style-loader \
     webpack webpack-cli webpack-dev-server webpack-merge
